# Configuration settings for the API
log_level: DEBUG
author:
  name: 
  overwrite: false
midi:
  targets:
    - "Line 6 Helix 9"
standards:
  setlist:
    casing: UPPERCASE
    replacements:
      " ":
        - "_"
      
  preset:
    casing: UPPERCASE
    replacements:
      " ":
        - "_"
      "Preset":
        - "New Preset"

  snapshot:
    casing: UPPERCASE
    replacements:
      " ":
        - "_"
      "Solo":
        - "lead"
